services:
  my-db:
    image: arm64v8/mysql:latest
    container_name: mysql
    command: --authentication_policy=caching_sha2_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: electronic_store
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3306:3306'
    expose:
        # Opens port 3306 on the container
      - '3306'
        # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
    # Names our volume
volumes:
  my-db:
    driver: local